


server:
  port: ${PORT:10000}

spring:
  application:
    name: booking-api-service

  
  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true

  
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

stripe:
  secret:
    key: ${STRIPE_SECRET_KEY}

logging:
  level:
    com.waygonway: INFO
    org.springframework.data.mongodb: WARN
    root: WARN
